`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: NUS
// Engineer: Shahzor Ahmad, Rajesh C Panicker
// 
// Create Date: 27.09.2016 10:59:44
// Design Name: 
// Module Name: MCycle
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
/* 
----------------------------------------------------------------------------------
--	(c) Shahzor Ahmad, Rajesh C Panicker
--	License terms :
--	You are free to use this code as long as you
--		(i) DO NOT post it on any public repository;
--		(ii) use it only for educational purposes;
--		(iii) accept the responsibility to ensure that your implementation does not violate any intellectual property of ARM Holdings or other entities.
--		(iv) accept that the program is provided "as is" without warranty of any kind or assurance regarding its suitability for any particular purpose;
--		(v) send an email to rajesh.panicker@ieee.org briefly mentioning its use (except when used for the course CG3207 at the National University of Singapore);
--		(vi) retain this notice in this file or any files derived from this.
----------------------------------------------------------------------------------
*/

module MCycle #(
    parameter width = 32 // Keep this at 4 to verify your algorithms with 4 bit numbers (easier). When using MCycle as a component in RV, generic map it to 32.
    )(
    input CLK,
    input RESET, // Connect this to the reset of the ARM processor.
    input Start, // Multi-cycle Enable. The control unit should assert this when an instruction with a multi-cycle operation is detected.
    input [1:0] MCycleOp, // Multi-cycle Operation. "00" for signed multiplication, "01" for unsigned multiplication, "10" for signed division, "11" for unsigned division. Generated by Control unit
    input [width-1:0] Operand1, // Multiplicand / Dividend
    input [width-1:0] Operand2, // Multiplier / Divisor
    output reg [width-1:0] MCycle_Result1, // LSW of Product / Quotient
    output reg [width-1:0] MCycle_Result2, // MSW of Product / Remainder
    output reg Busy // Set immediately when Start is set. Cleared when the Results become ready. This bit can be used to stall the processor while multi-cycle operations are on.
    );
    
// use the Busy signal to reset WE_PC to 0 in ARM.v (aka "freeze" PC). The two signals are complements of each other
// since the IDLE_PROCESS is combinational, instantaneously asserts Busy once Start is asserted
  
    parameter IDLE = 1'b0 ;  // will cause a warning which is ok to ignore - [Synth 8-2507] parameter declaration becomes local in MCycle with formal parameter declaration list...

    parameter COMPUTING = 1'b1 ; // this line will also cause the above warning
    reg state = IDLE ;
    reg n_state = IDLE ;
   
    reg done ;
    reg [7:0] count = 0 ; // assuming no computation takes more than 256 cycles.
    reg [2*width-1:0] temp_sum = 0 ;
    reg [2*width-1:0] shifted_op1 = 0 ;
    reg [2*width-1:0] shifted_op2 = 0 ;   
    reg result_sign = 0; // 0: positive, 1: negative  

    // For Booth's algorithm

    always@( state, done, Start, RESET ) begin : IDLE_PROCESS  
		// Note : This block uses non-blocking assignments to get around an unpredictable Verilog simulation behaviour.
        // default outputs
        Busy <= 1'b0 ;
        n_state <= IDLE ;
        
        // reset
        if(~RESET)
            case(state)
                IDLE: begin
                    if(Start) begin // note: a mealy machine, since output depends on current state (IDLE) & input (Start)
                        n_state <= COMPUTING ;
                        Busy <= 1'b1 ;
                    end
                end
                COMPUTING: begin
                    if(~done) begin
                        n_state <= COMPUTING ;
                        Busy <= 1'b1 ;
                    end
                end        
            endcase    
    end


    always@( posedge CLK ) begin : STATE_UPDATE_PROCESS // state updating
        state <= n_state ;    
    end

    
    always@( posedge CLK ) begin : COMPUTING_PROCESS // process which does the actual computation
        // n_state == COMPUTING and state == IDLE implies we are just transitioning into COMPUTING
        if( RESET | (n_state == COMPUTING & state == IDLE) ) begin // 2nd condition is true during the very 1st clock cycle of the multiplication
            count = 0 ;
            temp_sum = 0 ;
            result_sign = 0;

            /* sign extend the operands 
             * signed: sign extend by msb
             * unsigned: sign extend by zero
            */
            shifted_op1 = { {width{~MCycleOp[0] & Operand1[width-1]}}, Operand1 } ;   
            shifted_op2 = { {width{~MCycleOp[0] & Operand2[width-1]}}, Operand2 } ; 
            
            if (MCycleOp == 2'b10) begin // Signed Division
                result_sign = shifted_op1[width-1] ^ shifted_op2[width-1]; // Store result sign

                if (shifted_op1[width-1]) begin
                    shifted_op1 = ~shifted_op1 + 1; // Changed to unsigned (2's complement)
                end

                if (shifted_op2[width-1]) begin
                    shifted_op2 = ~shifted_op2 + 1; // Changed to unsigned (2's complement)
                end
            end

            if (MCycleOp[1]) begin // Division
                shifted_op2 = { shifted_op2[width-1 : 0], {width{1'b0}} };
            end
        end
        done <= 1'b0 ;   
        
        if( ~MCycleOp[1] ) begin // Multiply
            // if( ~MCycleOp[0] ), takes 2*'width' cycles to execute, returns signed(Operand1)*signed(Operand2)
            // if( MCycleOp[0] ), takes 'width' cycles to execute, returns unsigned(Operand1)*unsigned(Operand2)        
            
            /* Inefficient multiplier */
            if( shifted_op2[0] ) // add only if b0 = 1
                temp_sum = temp_sum + shifted_op1 ; // partial product for multiplication
                
            shifted_op2 = {1'b0, shifted_op2[2*width-1 : 1]} ;
            shifted_op1 = {shifted_op1[2*width-2 : 0], 1'b0} ;    
                
            // If (Unsigned Multiply and last) | (Signed Multiple and last)
            if( (MCycleOp[0] & count == width-1) | (~MCycleOp[0] & count == 2*width-1) ) // last cycle?
                done <= 1'b1 ;   
               
            count = count + 1;    
            
            /* Booth's algorithm

                ! ...0111...111110...
                !     ^         ^
                !     |         |
                ! 2^m       2^k

                ! 2^m + 2^(m-1) + 2^(m-2) + ... + 2^(k+1) + 2^k

                ! Proof

                ! Sum of geometric series:
                ! S = 2^k + 2^(k+1) + ... + 2^(m-1) + 2^m
                ! Multiply both sides by 2:
                ! 2S = 2^(k+1) + 2^(k+2) + ... + 2^m + 2^(m+1)
                ! Subtract S from 2S:
                ! S = 2^(m+1) - 2^k

            * Principle of operation:
             * 1. Strings of 0’s in the multiplier require no addition but just shifting and 
             * 2. a string of 1’s in the multiplier from bit weight 2^m to weight 2^k can be treated as 2^(m+1) to 2^k.
            
            
            * 3 cases:
            * 1. Subtracting on First 1 in a String of 1's (- 2^k):
                * When we encounter a '1' after a '0', it marks the start of a string of 1's.
                * We subtract the multiplicand from the partial product here.
                * This is equivalent to adding the negative of the multiplicand, setting up for the efficient handling of the string of 1's.


            * 2. Adding on First 0 After a String of 1's (2^m+1): 
                * When we encounter a '0' after a '1', it marks the end of a string of 1's.
                * We add the multiplicand to the partial product here.
                * This completes the operation of treating the string of 1's as 2^(m+1) - 2^k.


            * 3. No Change for Identical Bits:
                * When the current bit is the same as the previous bit (00 or 11), we don't modify the partial product.
                * This efficiently handles consecutive 0's or the middle of a string of 1's.
            
            * Implemenetaion:
              *  00 or 11: Shift right (A, Q, Q-1)
              *  01: Add Multiplicand to Accumulator, then shift right (A, Q, Q-1)
              *  10: Subtract Multiplicand from Accumulator, then shift right (A, Q, Q-1)
             */

            // case (shifted_op2[1:0]) // Check the last two bits of the multiplier
            //     2'b01: temp_sum = temp_sum + shifted_op1; // Add multiplicand to accumulator
            //     2'b10: temp_sum = temp_sum - shifted_op1; // Subtract multiplicand from accumulator
            //     default: ; // Do nothing for 2'b00 and 2'b11
            // endcase

            
        end    
        else begin // Supposed to be Divide. Change this to signed [ if(~MCycleOp[0]) ] and unsigned [ if(MCycleOp[0]) ] division.

            // Op1: dividend; Op2: divisor; Result = Op1/Op2
            if (shifted_op1 >= shifted_op2) begin
                shifted_op1 = shifted_op1 - shifted_op2;
                temp_sum = {temp_sum[width*2-2 : 0], 1'b1};
            end else begin
                temp_sum = {temp_sum[width*2-2 : 0], 1'b0};
            end

            // This is taken from lecture notes implementation
            // shifted_op1 = shifted_op1 - shifted_op2;
            // if (shifted_op1[width*2-1] == 1) begin
            //     shifted_op1 = shifted_op1 + shifted_op2;    // Restore original dividend
            //     temp_sum = {temp_sum[width*2-2 : 0], 1'b0};   // Shift left quotient
            // end else begin
            //     temp_sum = {temp_sum[width*2-2 : 0], 1'b1};   // Shift left quotient
            // end

            shifted_op2 = {1'b0, shifted_op2[width*2-1 : 1]}; // Shift right divisor

            // Check for "width" cycle of operations
            if (count == width) begin
                if (result_sign) begin
                    temp_sum = ~temp_sum + 1;
                end
                temp_sum[2*width-1 : width] = shifted_op1[width-1 : 0]; // Append remainder
                done <= 1'b1;
            end

            count = count + 1;        
        end
        
        MCycle_Result2 <= temp_sum[2*width-1 : width] ;    // Or remainder
        MCycle_Result1 <= temp_sum[width-1 : 0] ;          // Or quotient 
             
    end
   
endmodule
